#region Enums
enum PROCESS_CALLBACK {
	NONE,
	IDLE,
	PHYSICS,
	MANUAL
}
#endregion


#region Interal Signal Names
const INTERAL_TICK_CHANGED := &"INTERAL_TICK_CHANGED"
const INTERAL_PRIORITY_CHANGED := &"INTERAL_PRIORITY_CHANGED"
const INTERAL_CALLBACK_CHANGED := &"INTERAL_CALLBACK_CHANGED"
#endregion
